### PR TITLE
refactor: remove autopush crate

### PR DESCRIPTION
**Pull request by taddes**
Closes [SYNC-4036](https://mozilla-hub.atlassian.net/browse/SYNC-4036)

[SYNC-4036]: https://mozilla-hub.atlassian.net/browse/SYNC-4036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by jrconlin** [comment]
If I'm not mistaken, we can drop dependency for 
* `rusoto_core`
* `rusoto_credential`
* `rusoto_dynamodb`
* `serde_dynamodb`

With those out of the way, we might be able to bump up `rustls`, `hyper-rustls` and `hyper-apln` which could drop a few more of the audit exceptions.

**Comment by taddes** [comment]
Hey @jrconlin ! So `rusoto_core`, `rusoto_credential`, ` rusoto_dynamodb`, and `serde_dynamodb`are still used in `autopush-common` quite a bit. We've got the ticket filed for that here: [SYNC-4261](https://mozilla-hub.atlassian.net/browse/SYNC-4261), so if you're fine we'll resolve those in that ticket, as it may involve some changes related to removing the dynamodb related stuff that's beyond the scope of the `autopush` crate here. Taking those out now would break some things in autopush common (refs in mod.rs, retry.rs, etc). I can make note to bump up rustls, hyper-rustls and hyper-apln as you suggested in that one as well.

**Comment by pjenvey** [comment]
@jrconlin I logged a [separate issue for cleaning up autopush-common's deps](https://github.com/mozilla-services/autopush-rs/issues/702) just to keep this task as small as possible

**Comment by jrconlin** [comment]
Nope, fair enough. That work can be covered by the other ticket.

**Review by jrconlin — APPROVED** [review]

**Pull request merged**
